spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MovieStorage?createDatabaseIfNotExist=true
    username: root
    password: Pavan@2010
  jpa:
    show_sql: true
    hibernate:
      ddl_auto: update

server:
  port: 8000